<a href="https://colab.research.google.com/github/harishkumarkrr/Tensorflow2.0_DeepLearn/blob/master/SentimentAnalysisImdb_tensorflow2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Dense, Embedding


In [0]:
(x_train,y_train),(x_test,y_test)=imdb.load_data(num_words=20000)

In [64]:
print(x_train[0])

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]


In [0]:
x_train=pad_sequences(x_train,maxlen=100)
x_test=pad_sequences(x_test,maxlen=100)

In [66]:
print(x_test)

[[   0    0    0 ...   14    6  717]
 [   6  976 2078 ...  125    4 3077]
 [   4 5673    7 ...    9   57  975]
 ...
 [   0    0    0 ...   21  846 5518]
 [   0    1   11 ... 2302    7  470]
 [  56   96  346 ...   34 2005 2643]]


In [67]:
x_train.shape

(25000, 100)

In [68]:
x_test.shape

(25000, 100)

In [0]:
vocab_size=20000
embed_size=128

In [0]:
model=Sequential()
model.add(Embedding(vocab_size,embed_size, input_shape=(x_train.shape[1],)))
model.add(LSTM(units=60, activation='tanh'))
model.add(Dense(units=1, activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [81]:
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_9 (Embedding)      (None, 100, 128)          2560000   
_________________________________________________________________
lstm_6 (LSTM)                (None, 60)                45360     
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 61        
Total params: 2,605,421
Trainable params: 2,605,421
Non-trainable params: 0
_________________________________________________________________


In [86]:
history=model.fit(x_train, y_test, epochs=6, batch_size=128, validation_data=(x_test,y_test))

Train on 25000 samples, validate on 25000 samples
Epoch 1/6
25000/25000 [==============================] - 64s 3ms/sample - loss: 0.1007 - accuracy: 0.9632 - val_loss: 2.0135 - val_accuracy: 0.5063
Epoch 2/6
25000/25000 [==============================] - 64s 3ms/sample - loss: 0.0578 - accuracy: 0.9810 - val_loss: 2.3112 - val_accuracy: 0.5013
Epoch 3/6
25000/25000 [==============================] - 64s 3ms/sample - loss: 0.0367 - accuracy: 0.9885 - val_loss: 2.6496 - val_accuracy: 0.5045
Epoch 4/6
25000/25000 [==============================] - 65s 3ms/sample - loss: 0.0267 - accuracy: 0.9927 - val_loss: 2.7327 - val_accuracy: 0.5032
Epoch 5/6
25000/25000 [==============================] - 65s 3ms/sample - loss: 0.0246 - accuracy: 0.9925 - val_loss: 3.0073 - val_accuracy: 0.4998
Epoch 6/6
25000/25000 [==============================] - 65s 3ms/sample - loss: 0.0199 - accuracy: 0.9934 - val_loss: 3.0322 - val_accuracy: 0.5066


In [89]:
history.history

{'accuracy': [0.96324, 0.981, 0.98852, 0.99268, 0.99248, 0.99336],
 'loss': [0.10074569579064846,
  0.05782857698976993,
  0.036709977316856386,
  0.02673081932783127,
  0.02462934462726116,
  0.019869834605157375],
 'val_accuracy': [0.50632, 0.50128, 0.50448, 0.5032, 0.49976, 0.50664],
 'val_loss': [2.0134897024536134,
  2.3112221771240233,
  2.649630238876343,
  2.732661185913086,
  3.007310888900757,
  3.0321502275848387]}

In [0]:
rand_review=np.random.randint(10000, size=100)

In [0]:
x_test=np.append(x_test, [rand_review], axis=0)

In [114]:
model.predict(x_test)


array([[5.9425831e-05],
       [3.1312674e-01],
       [9.9995154e-01],
       ...,
       [5.5805949e-06],
       [5.5805949e-06],
       [5.5806004e-06]], dtype=float32)